### ISSUE TITLE
README 관련 대소문자/띄어쓰기 수정, 예제 오류 관련

### ISSUE THREAD

**Issue by GPM567** [SaidBySolo/DBKR-API-Python#6]
Patch note -> Patch Note가 낫지 않을까 생각합니다(뭐 표기법의 차이지만요).

핫픽스:모듈 임포트 오류 수정 -> 핫픽스: 모듈 임포트 오류 수정
으로 해두고
핫픽스일 때마다 앞에
'핫픽스: '를 붙이시는 게 낫지 않을까요?

Bot(not using class) 예제에
`import dbkrpy` 가 빠져있습니다.

discord(봇 서포트 디스코드) -> discord(봇 지원 디스코드 서버)
intro(봇 간단설명) -> intro(봇 소개) (공식 koreanbots 관리창 명칭입니다.)

봇개발자,카테고리는 리스트로 반환됩니다. -> 봇 개발자, 카테고리는 리스트로 반환됩니다.

**Comment by SaidBySolo** [comment]
Close in 6c1e711
