### ISSUE TITLE
[제안] 코드의 수정이 필요해보입니다.

### ISSUE THREAD

**Issue by wonderlandpark** [SaidBySolo/DBKR-API-Python#7]
현재 API의 URL인 `https://api.koreanbots.cf`를 모든 파일에 넣어두셨는데, 해당 url은 임시이며, 언제든 변경될 수 있습니다. 따라서 코드의 기동성이 떨어지는듯합니다. Config파일로 별도로 분리하여, 추가하시는게 좋을듯합니다.

**Comment by SaidBySolo** [comment]
P1
I Will fix it
